xcopy /y .\Dependencies\OGRE\bin\release\OgreMain.dll .\bin\release\
xcopy /y .\Dependencies\OGRE\bin\release\Plugin_CgProgramManager.dll .\bin\release\
xcopy /y .\Dependencies\OGRE\bin\release\cg.dll .\bin\release\
xcopy /y .\Dependencies\OGRE\bin\release\OIS.dll .\bin\release\
xcopy /y .\Dependencies\OGRE\bin\release\RenderSystem_GL.dll .\bin\release\
xcopy /y .\Dependencies\OGRE\bin\release\cg.dll .\bin\release\
xcopy /y .\Dependencies\OpenNI2\Redist\OpenNI2.dll .\bin\release\
xcopy /y .\Dependencies\OpenNI2\Redist\OpenNI.ini .\bin\release\
xcopy /y .\Dependencies\OpenNI2\Redist\OpenNI2 .\bin\release\OpenNI2 /S /E
xcopy /y .\Dependencies\MyGUI\bin\release\MyGUIEngine.dll .\bin\release\
xcopy /y .\Dependencies\FLANN\bin\release\flann.dll .\bin\release\
xcopy /y .\Dependencies\LeapMotion\lib\x86\Leap.dll .\bin\release\
xcopy /y .\Dependencies\OpenCV\bin\release\opencv_core247.dll .\bin\release\
xcopy /y .\Dependencies\OpenCV\bin\release\opencv_highgui247.dll .\bin\release\
xcopy /y .\Dependencies\OpenCV\bin\release\opencv_imgproc247.dll .\bin\release\
xcopy /y .\Dependencies\OpenCV\bin\release\opencv_calib3d247.dll .\bin\release\
xcopy /y .\Dependencies\OpenCV\bin\release\opencv_flann247.dll .\bin\release\
xcopy /y .\Dependencies\OpenCV\bin\release\opencv_features2d247.dll .\bin\release\
xcopy /y .\Dependencies\OpenCV\bin\release\opencv_video247.dll .\bin\release\
xcopy /y .\Dependencies\OGRE\bin\debug\OgreMain_d.dll .\bin\debug\
xcopy /y .\Dependencies\OGRE\bin\debug\Plugin_CgProgramManager_d.dll .\bin\debug\
xcopy /y .\Dependencies\OGRE\bin\debug\cg.dll .\bin\debug\
xcopy /y .\Dependencies\OGRE\bin\debug\OIS_d.dll .\bin\debug\
xcopy /y .\Dependencies\OGRE\bin\debug\RenderSystem_GL_d.dll .\bin\debug\
xcopy /y .\Dependencies\OGRE\bin\debug\cg.dll .\bin\debug\
xcopy /y .\Dependencies\OpenNI2\Redist\OpenNI2.dll .\bin\debug\
xcopy /y .\Dependencies\OpenNI2\Redist\OpenNI.ini .\bin\debug\
xcopy /y .\Dependencies\OpenNI2\Redist\OpenNI2 .\bin\debug\OpenNI2 /S /E
xcopy /y .\Dependencies\MyGUI\bin\debug\MyGUIEngine_d.dll .\bin\debug\
xcopy /y .\Dependencies\FLANN\bin\debug\flann.dll .\bin\debug\
xcopy /y .\Dependencies\LeapMotion\lib\x86\Leapd.dll .\bin\debug\
xcopy /y .\Dependencies\Common\msvcp100d.dll .\bin\debug\
xcopy /y .\Dependencies\Common\msvcr100d.dll .\bin\debug\
xcopy /y .\Dependencies\OpenCV\bin\debug\opencv_core247d.dll .\bin\debug\
xcopy /y .\Dependencies\OpenCV\bin\debug\opencv_highgui247d.dll .\bin\debug\
xcopy /y .\Dependencies\OpenCV\bin\debug\opencv_imgproc247d.dll .\bin\debug\
xcopy /y .\Dependencies\OpenCV\bin\debug\opencv_calib3d247d.dll .\bin\debug\
xcopy /y .\Dependencies\OpenCV\bin\debug\opencv_flann247d.dll .\bin\debug\
xcopy /y .\Dependencies\OpenCV\bin\debug\opencv_features2d247d.dll .\bin\debug\
xcopy /y .\Dependencies\OpenCV\bin\debug\opencv_video247d.dll .\bin\debug\